server:
  port: 8099
  servlet:
    context-path: /register
spring:
  application:
    name: HLB-Register
  security:
    user:
      name: hlb
      password: 123456
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/

