server:
  port: 8301
spring:
  application:
    name: Hlb-Gateway
  boot:
    admin:
      client:
        url: http://${hlb-monitor-admin}:8401
        username: hlb
        password: 123456
  cloud:
    gateway:
      routes:
        - id: Hlb-Auth
          uri: lb://Hlb-Auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/Hlb-Auth
        - id: Hlb-Server-System
          uri: lb://Hlb-Server-System
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/Hlb-Server-System
        - id: Hlb-Server-test
          uri: lb://Hlb-Server-Test
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: testfallback
                fallbackUri: forward:/fallback/Hlb-Server-Test
      default-filters:
        - StripPrefix=1

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://hlb:123456@${hlb-register}:8099/register/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: ALWAYS
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000